### ISSUE TITLE
Doesn't work with teamcity-messages

### ISSUE THREAD

**Issue by SBoudrias** [box/flaky#94]
Hey, looks like flaky is not working very well with `teamcity-messages` (under pytest for my case).

For some reason, every retries seems to log an empty line, and a failure status is logged alone on it's line without the test name.

Here's the log I'm encountering:

```
[14:37:58][Step 4/8] test.test_name
[14:37:59][test.test_name] 
[14:37:59][Step 4/8] 
[14:37:59][Step 4/8] 
[14:37:59][Step 4/8] 
[14:37:59][Step 4/8] FAILED
```

So I'm wondering if maybe test retries are missing some metadata allowing them to be correctly logged?

**Comment by SBoudrias** [comment]
I figured it'd be easier to reproduce with a code example, so here's one: https://github.com/SBoudrias/__teamcity-flaky-bug

**Comment by Jeff-Meadows** [comment]
I think this boils down to the fact that flaky has to do some "interesting" things to work with pytest.

flaky fudges the outcome of tests it wants to retry. pytest believes that an outcome can only be 'passed' or 'failed' (or a few others like skipped), and we must report one of those. So flaky reports a pass for a retry.

There's also a test status, which is a 3-tuple of outcome, 1-letter status, and word status (eg, `('passed', '.', 'PASSED')`). If that's empty, then it's ignored py pytest. This allows us to avoid inflating the count of tests that were run.


The way pytest does this is to call the `pytest_report_teststatus` hook from its `pytest_runtest_logreport` hook. It then uses the resulting status to categorize the test. If the teamcity messages took a similar approach, we'd be compatible.

Otherwise, perhaps flaky's architecture is fundamentally flawed for pytest. Pytest doesn't really have the notion of a 'retry' - that's why flaky exists. As a result, we're stuck with either reporting a fake pass, or with rewriting large parts of the pytest runner inside flaky.

**Comment by SBoudrias** [comment]
@Jeff-Meadows Hey, thanks for coming back on this.

From what you're saying, it looks like that means teamcity-message is not ignoring the empty test status.

**Comment by Jeff-Meadows** [comment]
That is correct, although I think I just figured out a way to fix this issue on flaky's end.
